<script setup lang="ts">
/**
 * 已认证的双分页视图，展示一个任务已提交的原始文件事实和扫描错误聚合。
 *
 * 路由参数/查询提供任务和独立游标。组件没有 props、发出事件或暴露的实例方法；挂载和游标变化会加载投影，
 * 分页操作会更新路由。
 */
import { onMounted, watch } from "vue"; import { useRoute, useRouter } from "vue-router";
import AsyncState from "../components/AsyncState.vue"; import CursorPager from "../components/CursorPager.vue"; import { useMediaFlowClient } from "../components/injectedClient"; import { useSessionStore } from "../app/session"; import { handleAuthenticatedFailure } from "../components/apiErrors"; import { useRawFiles } from "../features/raw-files/useRawFiles";
const client = useMediaFlowClient(); const route = useRoute(); const router = useRouter(); const session = useSessionStore(); const id = String(route.params.id); const feature = useRawFiles(client, id, { cursor: typeof route.query.cursor === "string" ? route.query.cursor : null, errorCursor: typeof route.query.errorCursor === "string" ? route.query.errorCursor : null }, (error) => handleAuthenticatedFailure(error, session, router, route.fullPath));
onMounted(() => Promise.all([feature.load(), feature.loadErrors()]));
watch(() => route.query.cursor, (cursor) => feature.load(typeof cursor === "string" ? cursor : undefined));
watch(() => route.query.errorCursor, (cursor) => feature.loadErrors(typeof cursor === "string" ? cursor : undefined));
function formatBytes(value: number): string { return `${value.toLocaleString('zh-CN')} B`; }
</script>
<template><main class="page-stack"><header class="page-header"><div><RouterLink :to="{ name: 'scan-task', params: { id } }">← 返回任务详情</RouterLink><h1>原始文件与扫描错误</h1></div></header><section aria-labelledby="files-heading"><h2 id="files-heading">原始文件</h2><AsyncState :state="feature.state.value" :error-message="feature.errorMessage.value" empty-message="此任务尚未发现原始文件" offline-message="当前离线，显示上次加载的原始文件" @retry="feature.load(typeof route.query.cursor === 'string' ? route.query.cursor : undefined)"><table data-wide-results><caption>原始文件结果</caption><thead><tr><th scope="col">相对路径</th><th scope="col">大小</th><th scope="col">修改时间</th></tr></thead><tbody><tr v-for="file in feature.files.value" :key="file.id"><td><code>{{ file.relative_path }}</code></td><td>{{ formatBytes(file.size_bytes) }}</td><td><time :datetime="file.modified_at">{{ file.modified_at }}</time></td></tr></tbody></table><ul data-mobile-results class="mobile-result-list"><li v-for="file in feature.files.value" :key="file.id"><strong><code>{{ file.relative_path }}</code></strong><span>{{ formatBytes(file.size_bytes) }}</span><time :datetime="file.modified_at">{{ file.modified_at }}</time></li></ul><CursorPager :has-previous-context="Boolean(route.query.cursor)" :next-cursor="feature.nextCursor.value" @previous="router.push({ query: { ...(typeof route.query.errorCursor === 'string' ? { errorCursor: route.query.errorCursor } : {}) } })" @next="router.push({ query: { ...(typeof route.query.errorCursor === 'string' ? { errorCursor: route.query.errorCursor } : {}), cursor: $event } })" /></AsyncState></section><section aria-labelledby="errors-heading"><h2 id="errors-heading">扫描错误</h2><AsyncState :state="feature.errorState.value" empty-message="没有扫描错误" offline-message="当前离线，显示上次加载的错误" @retry="feature.loadErrors(typeof route.query.errorCursor === 'string' ? route.query.errorCursor : undefined)"><ul class="card-list"><li v-for="error in feature.errors.value" :key="error.id" class="resource-card"><code>{{ error.relative_path }}</code><span>{{ error.code }} · {{ error.occurrences }} 次</span></li></ul><CursorPager :has-previous-context="Boolean(route.query.errorCursor)" :next-cursor="feature.nextErrorCursor.value" @previous="router.push({ query: { ...(typeof route.query.cursor === 'string' ? { cursor: route.query.cursor } : {}) } })" @next="router.push({ query: { ...(typeof route.query.cursor === 'string' ? { cursor: route.query.cursor } : {}), errorCursor: $event } })" /></AsyncState></section></main></template>
