<script setup lang="ts">
/**
 * 已认证扫描任务详情页，结合持久状态、重试/取消操作与 SSE 刷新恢复。
 *
 * 路由提供任务 ID 和返回列表上下文。组件没有 props、发出事件或暴露的实例方法；挂载时会在详情加载后开启同步，
 * 卸载时关闭所有事件监听器。
 */
import { inject, onBeforeUnmount, onMounted } from "vue"; import { useRoute, useRouter } from "vue-router";
import AsyncState from "../components/AsyncState.vue"; import ErrorSummary from "../components/ErrorSummary.vue"; import ScanStatusBadge from "../components/ScanStatusBadge.vue";
import { useMediaFlowClient } from "../components/injectedClient"; import { useSessionStore } from "../app/session"; import { handleAuthenticatedFailure } from "../components/apiErrors"; import { useScanTask } from "../features/scan-tasks/useScanTasks"; import { taskEventSourceFactoryKey, useTaskEvents } from "../features/scan-tasks/useTaskEvents";
const client = useMediaFlowClient(); const injectedFactory = inject(taskEventSourceFactoryKey, undefined); const route = useRoute(); const router = useRouter(); const session = useSessionStore(); const id = String(route.params.id); const failure = (error: unknown) => handleAuthenticatedFailure(error, session, router, route.fullPath);
const detail = useScanTask(client, id, failure); const events = useTaskEvents(detail, { eventSourceFactory: injectedFactory, onUnauthorized: () => failure(Object.assign(new Error("expired"), { status: 401 })) });
const backQuery = { ...(typeof route.query.status === "string" ? { status: route.query.status } : {}), ...(typeof route.query.cursor === "string" ? { cursor: route.query.cursor } : {}), ...(typeof route.query.context === "string" ? { context: route.query.context } : {}) };
onMounted(events.start); onBeforeUnmount(events.stop);
</script>
<template><main class="page-stack"><header class="page-header"><div><RouterLink :to="{ name: 'scan-tasks', query: backQuery }">← 返回扫描任务</RouterLink><h1>扫描任务详情</h1></div></header><ErrorSummary v-if="detail.actionError.value" data-action-error :message="detail.actionError.value.message" :focus-key="detail.actionErrorOccurrence.value" heading="任务操作未完成" /><AsyncState :state="detail.state.value" :error-message="detail.errorMessage.value" offline-message="当前离线，保留最近一次持久化结果并暂停写操作" @retry="detail.load"><article v-if="detail.task.value" class="detail-card"><div class="detail-heading"><ScanStatusBadge :status="detail.task.value.status" :recovering="detail.task.value.recovering" /><span v-if="events.connection.value === 'reconnecting'" role="status">正在恢复实时连接</span></div><p class="phase-live" aria-live="polite">{{ detail.task.value.recovering ? '任务正在恢复' : detail.task.value.status === 'running' ? '正在安全枚举目录' : `任务状态：${detail.task.value.status}` }}</p><dl class="count-grid" aria-live="off"><div><dt>已访问目录</dt><dd>{{ detail.task.value.counts.visited_directories }}</dd></div><div><dt>已观察文件</dt><dd>{{ detail.task.value.counts.observed_files }}</dd></div><div><dt>已跳过项目</dt><dd>{{ detail.task.value.counts.skipped_entries }}</dd></div><div><dt>错误</dt><dd>{{ detail.task.value.counts.errors }}</dd></div></dl><p v-if="detail.task.value.status === 'partial-success'">扫描部分成功：已保存可用结果，错误可单独查看并重试。</p><p v-else-if="detail.task.value.status === 'failed'">扫描失败，已保留此前提交的事实。</p><p v-else-if="detail.task.value.status === 'cancelled'">扫描已取消，已提交的结果仍然保留。</p><nav class="detail-actions" aria-label="任务操作"><RouterLink :to="{ name: 'scan-task-files', params: { id }, query: { view: 'files' } }">查看原始文件</RouterLink><RouterLink v-if="detail.task.value.counts.errors > 0" :to="{ name: 'scan-task-files', params: { id }, query: { view: 'errors' } }">查看扫描错误</RouterLink><button v-if="detail.showRetry.value" type="button" :disabled="!detail.canRetry.value" @click="detail.retry">重试扫描</button><button v-if="detail.showCancel.value" type="button" :disabled="!detail.canCancel.value" @click="detail.cancel">取消扫描</button></nav><p v-if="events.diagnostic.value" class="visually-hidden">{{ events.diagnostic.value }}</p></article></AsyncState></main></template>
